routes/web.php
Route::get('/proposal-kelompok/{id}/verifikasi-anggota', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationMember'])->name('proposal-kelompok.verification-member');
Route::get('/proposal-kelompok/{id}/verifikasi', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationShow'])->name('proposal-kelompok.verification-show');
Route::post('/proposal-kelompok/{id}/verifikasi', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationProcess'])->name('proposal-kelompok.verification-process');
Route::get('/proposal-kelompok/{id}/rangkuman-verifikasi', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationSummary'])->name('proposal-kelompok.verfication-summary');
// Penetapan Proposal
Route::get('/proposal-kelompok/{id}/penetapan', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'penetapanShow'])->name('proposal-kelompok.penetapan-show');
Route::post('/proposal-kelompok/{id}/penetapan', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'penetapanProcess'])->name('proposal-kelompok.penetapan-process');

// Pinjaman
Route::resource('pinjaman-kelompok', App\Http\Controllers\Pinjaman\Kelompok\PinjamanKelompokController::class);
// Detail pinjaman kelompok
Route::get('/pinjaman-kelompok-uep/{id}/detail', [App\Http\Controllers\Pinjaman\Kelompok\PinjamanKelompokController::class, 'detailUep'])->name('pinjaman-kelompok-uep.detail');
Route::get('/pinjaman-kelompok-spp/{id}/detail', [App\Http\Controllers\Pinjaman\Kelompok\PinjamanKelompokController::class, 'detailSpp'])->name('pinjaman-kelompok-spp.detail');
Route::resource('pinjaman-individu', App\Http\Controllers\Pinjaman\Individu\PinjamanIndividuController::class);


// Transaksi
Route::resource('angsuran-kelompok', App\Http\Controllers\Angsuran\Kelompok\PenerimaanAngsuranController::class);
Route::resource('angsuran-kelompok-uep', App\Http\Controllers\Angsuran\Kelompok\UEP\PenerimaanAngsuranUepController::class);
Route::resource('angsuran-kelompok-spp', App\Http\Controllers\Angsuran\Kelompok\SPP\PenerimaanAngsuranSppController::class);
Route::resource('angsuran-kelompok-lain', App\Http\Controllers\Angsuran\Kelompok\Lain\PenerimaanAngsuranLainController::class);

Route::resource('angsuran-individu', App\Http\Controllers\Angsuran\Individu\PenerimaanAngsuranController::class);
Route::resource('angsuran-individu-uep', App\Http\Controllers\Angsuran\Individu\UEP\PenerimaanAngsuranUepController::class);
Route::resource('angsuran-individu-spp', App\Http\Controllers\Angsuran\Individu\SPP\PenerimaanAngsuranSppController::class);
Route::resource('angsuran-individu-lain', App\Http\Controllers\Angsuran\Individu\Lain\PenerimaanAngsuranLainController::class);

// Penyaluran Kredit
Route::prefix('penyaluran-kredit')->group(function (){
    Route::prefix('kelompok')->group(function (){
        Route::get('/uep', 'App\Http\Controllers\PenyaluranKredit\kelompokController@uepIndex');
        Route::get('/spp', 'App\Http\Controllers\PenyaluranKredit\kelompokController@sppIndex');
    });

    Route::prefix('individu')->group(function (){
        Route::get('/uep', 'App\Http\Controllers\PenyaluranKredit\individuController@uepIndex');
        Route::get('/spp', 'App\Http\Controllers\PenyaluranKredit\individuController@sppIndex');
        Route::get('/perorangan', 'App\Http\Controllers\PenyaluranKredit\individuController@individualIndex');
    });
});


// Route::get('provinces', 'DependentDropdownController@provinces')->name('provinces');
Route::get('/provinces', [\App\Http\Controllers\DependantDropdownController::class, 'provinces'])->name('provinces');
Route::get('/cities', [\App\Http\Controllers\DependantDropdownController::class, 'cities'])->name('cities');
Route::get('/districts', [\App\Http\Controllers\DependantDropdownController::class, 'districts'])->name('districts');
Route::get('/villages', [\App\Http\Controllers\DependantDropdownController::class, 'villages'])->name('villages');

/* Route Laporan */
// Laporan Keuangan
Route::get('neraca-mikrofinance', [\App\Http\Controllers\LaporanKeuangan\LaporanKeuanganNeracaMikrofinanceController::class, 'index']);
Route::get('neraca-mikrofinance/cetak-pdf', [\App\Http\Controllers\LaporanKeuangan\LaporanKeuanganNeracaMikrofinanceController::class, 'cetakPdf']);
Route::get('rugi-laba-mikrofinance', [\App\Http\Controllers\LaporanKeuangan\LaporanKeuanganRugiLabaMikrofinanceController::class, 'index']);
Route::get('rugi-laba-mikrofinance/cetak-pdf', [\App\Http\Controllers\LaporanKeuangan\LaporanKeuanganRugiLabaMikrofinanceController::class, 'cetakPdf']);

//Kelompok
Route::prefix('laporan-kelompok')->namespace('Laporan\Kelompok')->group(function () {
    Route::get('laporan-kelompok-spkp', [\App\Http\Controllers\Laporan\Kelompok\LaporanKelompokSPKP::class, 'index'])->name('lap-kel-spkp');
    Route::get('laporan-kelompok-uep', [\App\Http\Controllers\Laporan\Kelompok\LaporanKelompokUEP::class, 'index'])->name('lap-kel-uep');
});

//Buku Pembantu
Route::prefix('laporan-buku-pembantu')->namespace('Laporan\BukuPembantu')->group(function () {
    Route::get('daftar-BDD', [\App\Http\Controllers\Laporan\BukuPembantu\BukuDaftarBDD::class, 'index'])->name('daftar-bdd');
    Route::get('daftar-inventaris', [\App\Http\Controllers\Laporan\BukuPembantu\BukuDaftarInventaris::class, 'index'])->name('daftar-inven');
    Route::get('daftar-aktiva-tetap', [\App\Http\Controllers\Laporan\BukuPembantu\BukuDaftarAktivaTetap::class, 'index'])->name('daftar-aktiv');
    Route::get('daftar-biaya-lain', [\App\Http\Controllers\Laporan\BukuPembantu\BukuDaftarBiayaLain::class, 'index'])->name('daftar-biaya');
    Route::get('daftar-perguliran-SPP', [\App\Http\Controllers\Laporan\BukuPembantu\BukuDaftarPerguliranSPP::class, 'index'])->name('daftar-gulir-spp');
    Route::get('daftar-perguliran-UEP', [\App\Http\Controllers\Laporan\BukuPembantu\BukuDaftarPerguliranUEP::class, 'index'])->name('daftar-gulir-uep');
    Route::get('daftar-pemb_ITW', [\App\Http\Controllers\Laporan\BukuPembantu\BukuDaftarITW::class, 'index'])->name('daftar-pemb_itw');
});

//Rekap Pinjaman UEP
Route::prefix('laporan-pinjaman-UEP')->group(function () {

    #Kelompok
    Route::prefix('/')->namespace('Laporan\PinjamanUEP\Kelompok')->group(function () {
        Route::get('daftar-LPP-UEP-kelompok', [\App\Http\Controllers\Laporan\PinjamanUEP\Kelompok\LPP_UEP::class, 'index'])->name('lpp-uep-kelompok');
        Route::get('daftar-kolektibilitas-UEP-kelompok', [\App\Http\Controllers\Laporan\PinjamanUEP\Kelompok\KolektibilitasUEP::class, 'index'])->name('kolek-uep-kelompok');
        Route::get('daftar-penghapusan-UEP-kelompok', [\App\Http\Controllers\Laporan\PinjamanUEP\Kelompok\PenghapusanUEP::class, 'index'])->name('hapus-uep-kelompok');
        Route::get('daftar-UEP-lain-kelompok', [\App\Http\Controllers\Laporan\PinjamanUEP\Kelompok\LPP_Lain::class, 'index'])->name('uep-lain-kelompok');
    });

    #Individu
    Route::prefix('/')->namespace('Laporan\PinjamanUEP\Individu')->group(function () {
        Route::get('daftar-LPP-UEP-individu', [\App\Http\Controllers\Laporan\PinjamanUEP\Individu\LPP_UEP::class, 'index'])->name('lpp-uep-individu');
        Route::get('daftar-kolektibilitas-UEP-individu', [\App\Http\Controllers\Laporan\PinjamanUEP\Individu\KolektibilitasUEP::class, 'index'])->name('kolek-uep-individu');
    });
});

//Rekap Pinjaman SPP
Route::prefix('laporan-pinjaman-SPP')->group(function () {

    #Kelompok
    Route::prefix('/')->namespace('Laporan\PinjamanSPP\Kelompok')->group(function () {
        Route::get('LPP-SPP-kelompok', [\App\Http\Controllers\Laporan\PinjamanSPP\Kelompok\LPP_SPP::class, 'index'])->name('lpp-spp-kelompok');
        Route::get('kolektibilitas-SPKP-kelompok', [\App\Http\Controllers\Laporan\PinjamanSPP\Kelompok\KolektibilitasSPKP::class, 'index'])->name('kolek-spp-kelompok');
        Route::get('penghapusan-SPKP-kelompok', [\App\Http\Controllers\Laporan\PinjamanSPP\Kelompok\PenghapusanSPKP::class, 'index'])->name('hapus-spp-kelompok');
        Route::get('SPKP-lain-kelompok', [\App\Http\Controllers\Laporan\PinjamanSPP\Kelompok\LPP_SPKPLain::class, 'index'])->name('spp-lain-kelompok');
    });

    #Individu
    Route::prefix('/')->namespace('Laporan\PinjamanSPP\Individu')->group(function () {
        Route::get('LPP-SPP-individu', [\App\Http\Controllers\Laporan\PinjamanSPP\Individu\LPP_SPP::class, 'index'])->name('lpp-spp-individu');
        Route::get('kolektibilitas-SPP-individu', [\App\Http\Controllers\Laporan\PinjamanSPP\Individu\KolektibilitasSPP::class, 'index'])->name('kolek-spp-individu');
    });
});

//Buku Bank
Route::resource('buku-bank-spp', App\Http\Controllers\Transaksi\BukuBank\BukuBankSppController::class);
Route::resource('buku-bank-uep', App\Http\Controllers\Transaksi\BukuBank\BukuBankUepController::class);
Route::resource('buku-bank-ops', App\Http\Controllers\Transaksi\BukuBank\BukuBankOpsController::class);
Route::resource('buku-bank-perorangan', App\Http\Controllers\Transaksi\BukuBank\BukuBankPeroranganController::class);

//Laporan UEP
Route::resource('laporan-uep-kas', App\Http\Controllers\Laporan\UEP\LaporanUepKasController::class);
Route::post('laporan-uep-kas-cetak', [\App\Http\Controllers\Laporan\UEP\LaporanUepKasController::class, 'cetakLaporan']);
Route::resource('laporan-uep-bank', App\Http\Controllers\Laporan\UEP\LaporanUepBankController::class);
Route::post('laporan-uep-bank-cetak', [\App\Http\Controllers\Laporan\UEP\LaporanUepBankController::class, 'cetakLaporan']);

// SPP
Route::get('kas-spkp',[\App\Http\Controllers\SppController::class, 'kasSpkp'])->name('kasSpkp');
Route::get('bank-spkp',[\App\Http\Controllers\SppController::class, 'bankSpkp'])->name('bankSpkp');

// Perorangan
Route::get('kas-perorangan',[\App\Http\Controllers\PeroranganController::class, 'kasPerorangan'])->name('kasPerorangan');

app/Http/Controllers/Perorangan/PeroranganBankPeroranganController.php
<?php

namespace App\Http\Controllers\Perorangan;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use PDF;
class PeroranganBankPeroranganController extends Controller
{
    public function index(){
        $rand = rand(100000000000, 999999999);
        return view('\perorangan\bankPerorangan', ['random' => $rand])->with([
            'title' => 'Perorangan - Bank Perorangan'
        ]);
    }
    public function cetakPdf(){
        $rand = rand(100000000000, 999999999);
        $pdf = PDF::loadview('\perorangan\bankPeroranganCetak', ['random' => $rand])->setPaper('a4', 'landscape');
        return $pdf->stream();
    }
}

app/Http/Controllers/Perorangan/PeroranganKasPeroranganController.php
<?php

namespace App\Http\Controllers\Perorangan;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use PDF;
class PeroranganKasPeroranganController extends Controller
{
    public function index(){
        $rand = rand(100000000000, 999999999);
        return view('\perorangan\kasPerorangan', ['random' => $rand])->with([
            'title' => 'Perorangan - Kas Perorangan'
        ]);;
    }
    public function cetakPdf(){
        $rand = rand(100000000000, 999999999);
        $pdf = PDF::loadview('\perorangan\kasPeroranganCetak', ['random' => $rand])->setPaper('a4', 'landscape');
        return $pdf->stream();
    }
}

app/Http/Controllers/PeroranganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PeroranganController extends Controller
{
    public function kasPerorangan(){
        $rand = rand(100000, 5000000);
        return view('\perorangan\kasPerorangan', ['random' => $rand]);
    }

    public function bankPerorangan(){
        $rand = rand(100000, 5000000);
        return view('\perorangan\bankPerorangan', ['random' => $rand]);
    }
}

app/Http/Controllers/Transaksi/BukuBank/BukuBankOpsController.php
<?php

namespace App\Http\Controllers\Transaksi\BukuBank;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BukuBankOpsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Transaksi.BukuBank.OPS.BukuBankOpsShow')->with([
            'title'=> 'Buku Bank OPS',
            // 'count' => $count
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Transaksi.BukuBank.OPS.BukuBankOpsCreate')->with([
            'title' => 'Tambah Buku Bank OPS'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('Transaksi.BukuBank.OPS.BukuBankOpsEdit',)->with([
            'title' => 'Edit Buku Bank OPS'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Transaksi/BukuBank/BukuBankPeroranganController.php
<?php

namespace App\Http\Controllers\Transaksi\BukuBank;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BukuBankPeroranganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Transaksi.BukuBank.Perorangan.BukuBankPeroranganShow')->with([
            'title'=> 'Buku Bank Perorangan',
            // 'count' => $count
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Transaksi.BukuBank.Perorangan.BukuBankPeroranganCreate')->with([
            'title' => 'Tambah Buku Bank Perorangan'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('Transaksi.BukuBank.Perorangan.BukuBankPeroranganEdit',)->with([
            'title' => 'Edit Buku Bank Perorangan'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Transaksi/BukuBank/Perorangan/BukuBankPeroranganCreate.blade.php
@extends('layouts.master')

@section('title'){{$title}} @endsection

@section('css')
<!-- select2 css -->
<link href="{{ url('assets/libs/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />

<!-- dropzone css -->
<link href="{{ url('assets/libs/dropzone/dropzone.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

@component('components.breadcrumb')
@slot('li_1') Buku Bank @endslot
@slot('title') Tambah Perorangan @endslot
@endcomponent
<form action="{{ route('pengaturan-desa.store') }}"  method="post" class="custom-validation">
    @csrf
<div class="row">
    <div class="col-12">

        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <div class="row">
                    <div class="col-sm-6">
                        <div class="mb-3">
                            <label for="tanggal">Tanggal</label>
                            <input id="tanggal" name="tanggal" type="date" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="keterangan">Keterangan</label>
                            <input id="keterangan" name="keterangan" type="text" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="bukti">Bukti</label>
                            <input id="bukti" name="bukti" type="text" class="form-control" disabled>
                        </div>
                        <div class="mb-3">
                            <label for="nominal">Nominal</label>
                            <input id="nominal" name="nominal" type="number" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="nama">Kode Transaksi</label>
                            <select class="form-control select2" name="desa" id="desa" required>
                                <option value="" selected disabled>--Masuk</option>
                                <option value="Bunga Bank">12302 - Bunga Bank</option>
                                <option value="" selected disabled>--Keluar</option>
                                <option value="Penarikan">12303 - Penarikan</option>
                                <option value="Pajak">12304 - Pajak</option>
                                <option value="Biaya Adm">12305 - Biaya Adm</option>
                            </select>
                        </div>
                    </div>
                    <div class="d-flex flex-wrap gap-2">
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Save Changes</button>
                        <a  href="{{ URL('buku-bank-perorangan') }}"><button type="button"  class="btn btn-secondary waves-effect waves-light">Cancel</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
    <!-- end row -->

@endsection
@section('script')


<!-- select 2 plugin -->
<script src="{{ url('assets/libs/select2/select2.min.js') }}"></script>

<!-- dropzone plugin -->
<script src="{{ url('assets/libs/dropzone/dropzone.min.js') }}"></script>

<!-- init js -->
<script src="{{ url('assets/js/pages/ecommerce-select2.init.js') }}"></script>
<script src="{{ URL::asset('/assets/libs/parsleyjs/parsleyjs.min.js') }}"></script>
<script src="{{ URL::asset('/assets/js/pages/form-validation.init.js') }}"></script>
<script type="text/javascript">
    $('#desa').change(function(){
        var desa = $('#desa').val();
        if(desa == 'other'){
           $('#fieldLainnya').show();
           $('#desaLainnya').attr('required',true);
        }else{
            $('#fieldLainnya').hide();
            $('#desaLainnya').val('');
             $('#desaLainnya').attr('required',false);
        }
    })
  </script>

@endsection

resources/views/Transaksi/BukuBank/Perorangan/BukuBankPeroranganEdit.blade.php
@extends('layouts.master')

@section('title'){{$title}} @endsection

@section('css')
<!-- select2 css -->
<link href="{{ url('assets/libs/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />

<!-- dropzone css -->
<link href="{{ url('assets/libs/dropzone/dropzone.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

@component('components.breadcrumb')
@slot('li_1') Buku Bank @endslot
@slot('title') Edit Perorangan @endslot
@endcomponent
<form action="{{ route('pengaturan-desa.update',1) }}"  method="post" class="custom-validation">
    @csrf
    @method('PUT')
<div class="row">
    <div class="col-12">

        <div class="card">
            <div class="card-body">

                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <div class="row">
                    <div class="col-sm-6">
                    <div class="mb-3">
                            <label for="tanggal">Tanggal</label>
                            <input id="tanggal" name="tanggal" type="date" value="2018-03-12" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="keterangan">Keterangan</label>
                            <input id="keterangan" name="keterangan" type="text" value="Tarik Dari Rekening" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="bukti">Bukti</label>
                            <input id="bukti" name="bukti" type="text" value="1221812003" class="form-control" disabled>
                        </div>
                        <div class="mb-3">
                            <label for="nominal">Nominal</label>
                            <input id="nominal" name="nominal" type="number" value="10000000" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="nama">Kode Transaksi</label>
                            <select class="form-control select2" name="desa" id="desa" required>
                                <option value="" disabled>--Masuk</option>
                                <option value="Bunga Bank" >12302 - Bunga Bank</option>
                                <option value=""  disabled>--Keluar</option>
                                <option value="Penarikan" selected>12303 - Penarikan</option>
                                <option value="Pajak">12304 - Pajak</option>
                                <option value="Biaya Adm">12305 - Biaya Adm</option>
                            </select>
                        </div>
                    </div>
                    <div class="d-flex flex-wrap gap-2">
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Save Changes</button>
                        <a  href="{{ URL('buku-bank-perorangan') }}"><button type="button"  class="btn btn-secondary waves-effect waves-light">Cancel</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
    <!-- end row -->

@endsection
@section('script')


<!-- select 2 plugin -->
<script src="{{ url('assets/libs/select2/select2.min.js') }}"></script>

<!-- dropzone plugin -->
<script src="{{ url('assets/libs/dropzone/dropzone.min.js') }}"></script>

<!-- init js -->
<script src="{{ url('assets/js/pages/ecommerce-select2.init.js') }}"></script>
<script src="{{ URL::asset('/assets/libs/parsleyjs/parsleyjs.min.js') }}"></script>
<script src="{{ URL::asset('/assets/js/pages/form-validation.init.js') }}"></script>
<script type="text/javascript">
    $('#desa').change(function(){
        var desa = $('#desa').val();
        if(desa == 'other'){
           $('#fieldLainnya').show();
           $('#desaLainnya').attr('required',true);
        }else{
            $('#fieldLainnya').hide();
            $('#desaLainnya').val('');
             $('#desaLainnya').attr('required',false);
        }
    })
  </script>

@endsection

resources/views/Transaksi/BukuBank/Perorangan/BukuBankPeroranganShow.blade.php
@extends('layouts.master')

@section('title') {{ $title }} @endsection

@section('css')
    <!-- DataTables -->
    <link href="{{ URL::asset('/assets/libs/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    @component('components.breadcrumb')
        @slot('li_1') Buku Bank @endslot
        @slot('title') Perorangan @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @if ($message = Session::get('success'))
                    <div class="alert border-0 border-start border-5 border-primary alert-dismissible fade show">
                        <div>{{ $message }}</div>
                    </div>
	                @endif
                    {{-- <h4 class="card-title">Default Datatable</h4>
                    <p class="card-title-desc">DataTables has most features enabled by
                        default, so all you need to do to use it with your own tables is to call
                        the construction function: <code>$().DataTable();</code>.
                    </p> --}}
                    <p>
                        <a class="btn btn-primary btn-sm" href="{{ route('buku-bank-perorangan.create') }}">Tambah</a>
                    </p>
                    <h1 align="right">Rp. 43.131.821</h1>
                    <table id="datatable" class="table table-bordered dt-responsive  nowrap w-100">
                        <thead>
                            <tr>
                                <th>Tanggal</th>
                                <th>Keterangan</th>
                                <th>Bukti</th>
                                <th>Masuk</th>
                                <th>Keluar</th>
                                <th>Petugas</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>24-10-2018</td>
                                <td>Pajak Bank</td>
                                <td>1221810002</td>
                                <td>0</td>
                                <td>3.00.000</td>
                                <td>ADE SUTINI</td>
                                <td><a class="btn btn-outline-primary btn-sm" href="{{ route('buku-bank-ops.edit',1) }}">Edit</a>
                                <a class="btn btn-outline-danger btn-sm" href="#">Hapus</a>
                                </td>
                            </tr>
                            <tr>
                                <td>03-12-2018</td>
                                <td>Tarik Dari Rekening</td>
                                <td>1221812003</td>
                                <td>0</td>
                                <td>10.000.000</td>
                                <td>ADE SUTINI</td>
                                <td><a class="btn btn-outline-primary btn-sm" href="{{ route('buku-bank-perorangan.edit',2) }}">Edit</a>
                                <a class="btn btn-outline-danger btn-sm" href="#">Hapus</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->



@endsection
@section('script')
    <!-- Required datatable js -->
    <script src="{{ URL::asset('/assets/libs/datatables/datatables.min.js') }}"></script>
    <script src="{{ URL::asset('/assets/libs/jszip/jszip.min.js') }}"></script>
    <script src="{{ URL::asset('/assets/libs/pdfmake/pdfmake.min.js') }}"></script>
    <!-- Datatable init js -->
    <script src="{{ URL::asset('/assets/js/pages/datatables.init.js') }}"></script>
@endsection