routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/config-clear', function () {
    Artisan::call('config:clear');
    return 'Configuration cache cleared!';
});

Route::get('/config-cache', function () {
    Artisan::call('config:cache');
    return 'Configuration cache cleared! <br> Configuration cached successfully!';
});

Route::get('/cache-clear', function () {
    Artisan::call('cache:clear');
    return 'Application cache cleared!';
});

Route::get('/view-cache', function () {
    Artisan::call('view:cache');
    return 'Compiled views cleared! <br> Blade templates cached successfully!';
});

Route::get('/view-clear', function () {
    Artisan::call('view:clear');
    return 'Compiled views cleared!';
});

Route::get('/route-cache', function () {
    Artisan::call('route:cache');
    return 'Route cache cleared! <br> Routes cached successfully!';
});

Route::get('/route-clear', function () {
    Artisan::call('route:clear');
    return 'Route cache cleared!';
});

Route::get('/storage-link', function () {
    Artisan::call('storage:link');
    return 'The links have been created.';
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'root'])->name('root');
// Route::get('/testing', [App\Http\Controllers\Pengaturan\PengaturanProfileController::class, 'index'])->name('index');

// Master Data
Route::resource('master-jenis-kegiatan', App\Http\Controllers\Master\MasterJenisKegiatanController::class);
Route::resource('master-jenis-usaha', App\Http\Controllers\Master\MasterJenisUsahaController::class);
Route::resource('master-pekerjaan', App\Http\Controllers\Master\MasterPekerjaanController::class);
Route::resource('master-agama', App\Http\Controllers\Master\MasterAgamaController::class);
Route::resource('master-kekeluargaan', App\Http\Controllers\Master\MasterKekeluargaanController::class);
Route::resource('master-status-perkawinan', App\Http\Controllers\Master\MasterStatusPerkawinanController::class);

//Update User Details
Route::post('/update-profile/{id}', [App\Http\Controllers\HomeController::class, 'updateProfile'])->name('updateProfile');
Route::post('/update-password/{id}', [App\Http\Controllers\HomeController::class, 'updatePassword'])->name('updatePassword');

// Route::get('{any}', [App\Http\Controllers\HomeController::class, 'index1'])->name('index1');

//Language Translation
Route::get('index/{locale}', [App\Http\Controllers\HomeController::class, 'lang']);

// Pengaturan
Route::resource('pengaturan-profile', App\Http\Controllers\Pengaturan\PengaturanProfileController::class);
Route::resource('pengaturan-kecamatan', App\Http\Controllers\Pengaturan\PengaturanKecamatanController::class);
Route::resource('pengaturan-desa', App\Http\Controllers\Pengaturan\PengaturanDesaController::class);
Route::prefix('pengaturan')->group(function () {
    Route::prefix('pengurus')->group(function () {
        Route::get('/', 'App\Http\Controllers\Pengaturan\PengurusController@index')->name('listPengurus');
        Route::get('/create', 'App\Http\Controllers\Pengaturan\PengurusController@create')->name('createPengurus');
        Route::get('/edit/{id}', 'App\Http\Controllers\Pengaturan\PengurusController@edit')->name('editPengurus');
        Route::post('/submit', 'App\Http\Controllers\Pengaturan\PengurusController@submit')->name('submitPengurus');
        Route::delete('/delete/{id}', 'App\Http\Controllers\Pengaturan\PengurusController@index')->name('deletePengurus');
    });
});

// Akuntansi
Route::prefix('akuntansi')->group(function (){
    Route::get('periode-akuntansi', 'App\Http\Controllers\Akuntansi\PeriodeAkuntansiController@index');
    Route::prefix('saldo-awal')->group(function (){
        Route::get('/', 'App\Http\Controllers\Akuntansi\SaldoAwalController@index');
        Route::get('/create', 'App\Http\Controllers\Akuntansi\SaldoAwalController@create');
        Route::post('/submit', 'App\Http\Controllers\Akuntansi\SaldoAwalController@submit')->name('saldoAwalSubmit');
    });
    Route::prefix('hibah')->group(function (){
        Route::get('/', 'App\Http\Controllers\Akuntansi\HibahController@index');
        Route::get('/create', 'App\Http\Controllers\Akuntansi\HibahController@create');
    });
    Route::prefix('tutup-buku')->group(function(){
        Route::get('/validator', 'App\Http\Controllers\Akuntansi\TutupBukuController@validator');
        Route::get('/pembagian-surplus', 'App\Http\Controllers\Akuntansi\TutupBukuController@pembagianSurplus');
        Route::get('/perubahan-surplus', 'App\Http\Controllers\Akuntansi\TutupBukuController@perubahanSurplus');
        Route::get('/saldo-awal', 'App\Http\Controllers\Akuntansi\TutupBukuController@saldoAwal');
        Route::get('/proses-tutup-buku', 'App\Http\Controllers\Akuntansi\TutupBukuController@tutupBuku');
        Route::get('/neraca-awal', 'App\Http\Controllers\Akuntansi\TutupBukuController@neracaAwal');
        Route::post('/neraca-awal', 'App\Http\Controllers\Akuntansi\TutupBukuController@laporanNeracaAwal')->name('laporanNeracaAwal');
    });
});

// User
Route::prefix('user')->group(function (){
    Route::get('/', 'App\Http\Controllers\User\UserController@index')->name('user.show');
    Route::get('/create', 'App\Http\Controllers\User\UserController@create')->name('userCreate');
    Route::post('/submit', 'App\Http\Controllers\User\UserController@submit')->name('userSubmit');
    Route::get('user-detail/{id}', 'App\Http\Controllers\User\UserController@userDetail')->name('user.detail');
    Route::get('user-edit/{id}', 'App\Http\Controllers\User\UserController@userEditDetail')->name('user.edit.detail');
    Route::post('edit', 'App\Http\Controllers\User\UserController@submitEdit')->name('user.update');
    Route::delete('delete/{id}', 'App\Http\Controllers\User\UserController@delete')->name('user.delete');
});


// Keanggotaan 
Route::resource('kelompok-list', App\Http\Controllers\Anggota\Kelompok\KelompokListController::class);
Route::resource('kelompok-anggota', App\Http\Controllers\Anggota\Kelompok\KelompokAnggotaController::class);
Route::resource('individu-anggota', App\Http\Controllers\Anggota\Individu\IndividuAnggotaController::class);

// Proposal
Route::resource('proposal-kelompok', App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class);
Route::post('/tambah-anggota', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'addMember'])->name('proposal-kelompok.add-member');
// Detail kelompok
Route::get('/proposal-kelompok/{id}/detail', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'detail'])->name('proposal-kelompok.detail');
// Registrasi Proposal
Route::post('/tambah-anggota', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'addMember'])->name('proposal-kelompok.add-member');
Route::get('/proposal-kelompok/{id}/register', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'registering'])->name('proposal-kelompok.registering');
Route::post('/proposal-kelompok/{id}/register', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'registerProcess'])->name('proposal-kelompok.register-process');
Route::get('/proposal-kelompok/{id}/dokumen', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'document'])->name('proposal-kelompok.register-document');
// Verifikasi Proposal
Route::get('/proposal-kelompok/{id}/verifikasi-anggota', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationMember'])->name('proposal-kelompok.verification-member');
Route::get('/proposal-kelompok/{id}/verifikasi', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationShow'])->name('proposal-kelompok.verification-show');
Route::post('/proposal-kelompok/{id}/verifikasi', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationProcess'])->name('proposal-kelompok.verification-process');
Route::get('/proposal-kelompok/{id}/rangkuman-verifikasi', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationSummary'])->name('proposal-kelompok.verfication-summary');
// Penetapan Proposal
Route::get('/proposal-kelompok/{id}/penetapan', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'penetapanShow'])->name('proposal-kelompok.penetapan-show');
Route::post('/proposal-kelompok/{id}/penetapan', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'penetapanProcess'])->name('proposal-kelompok.penetapan-process');

// Pinjaman
Route::resource('pinjaman-kelompok', App\Http\Controllers\Pinjaman\Kelompok\PinjamanKelompokController::class);
// Detail pinjaman kelompok
Route::get('/pinjaman-kelompok-uep/{id}/detail', [App\Http\Controllers\Pinjaman\Kelompok\PinjamanKelompokController::class, 'detailUep'])->name('pinjaman-kelompok-uep.detail');
Route::get('/pinjaman-kelompok-spp/{id}/detail', [App\Http\Controllers\Pinjaman\Kelompok\PinjamanKelompokController::class, 'detailSpp'])->name('pinjaman-kelompok-spp.detail');
Route::resource('pinjaman-individu', App\Http\Controllers\Pinjaman\Individu\PinjamanIndividuController::class);


// Transaksi
Route::resource('angsuran-kelompok', App\Http\Controllers\Angsuran\Kelompok\PenerimaanAngsuranController::class);
Route::resource('angsuran-kelompok-uep', App\Http\Controllers\Angsuran\Kelompok\UEP\PenerimaanAngsuranUepController::class);

app/Http/Controllers/Pengaturan/PengaturanDesaController.php
<?php

namespace App\Http\Controllers\Pengaturan;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class PengaturanDesaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $data = DB::table('tb_desa')->get();
        // $count = DB::table('tb_profil')->count();
        return view('Pengaturan.Desa.desaShow',['data' => $data])->with([
            'title'=> 'Desa',
            // 'count' => $count
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $desaCode = DB::table('tb_profil')->get();
       $desa = getDesa($desaCode[0]->desa_upk);

        return view('Pengaturan.Desa.desaCreate',['desaCode' => $desa])->with([
            'title' => 'Desa'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $desaLainnya = $request->desaLainnya;
        if($desaLainnya){
            $codeDesa =  $string = rand(0,9999999);
            $namaDesa = $desaLainnya;
            $lainnya = 1;
        }else{
        $codeDesa = $request->desa;
        $getNameDesa = getNameDesa($codeDesa);
        $namaDesa = $getNameDesa[0]->name;
        $lainnya = 0;
        }
        $alamat = $request->alamat;
        $telp = $request->telp;
        $kepalaDesa = $request->kepalaDesa;
        $status = $request->status;

        $request->validate([
            'desa' => 'required|unique:tb_desa,kode'
        ]);

        DB::table('tb_desa')->insert([
            'kode' => $codeDesa,
            'nama_desa' => $namaDesa,
            'kepala_desa' => $kepalaDesa,
            'telp' => $telp,
            'alamat_desa' => $alamat,
            'status' => $status,
            'lainnya' => $lainnya,
            'created_at' => Carbon::now()
        ]);

        return redirect('pengaturan-desa')->with([
            'title' => 'Desa'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $profile = DB::table('tb_profil')->get();
        $data = DB::table('tb_desa')->where('id',$id)->get();
        $desa = getDesa($profile[0]->desa_upk);
        return view('Pengaturan.Desa.desaEdit',['data' => $data,'desa'=>$desa])->with([
            'title' => 'Edit Desa'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {



        $desaLainnya = $request->desaLainnya;
        if($desaLainnya){
            $codeDesa =  $string = rand(0,9999999);
            $namaDesa = $desaLainnya;
            $lainnya = 1;
        }else{
        $codeDesa = $request->desa;
        $getNameDesa = getNameDesa($codeDesa);
        $namaDesa = $getNameDesa[0]->name;
        $lainnya = 0;
        }
        $alamat = $request->alamat;
        $telp = $request->telp;
        $kepalaDesa = $request->kepalaDesa;
        $status = $request->status;

        // $request->validate([
        //     'desa' => 'required|unique:tb_desa,kode'
        // ]);

        $cek = DB::table('tb_desa')->where('id',$id)->get();
        $cekLainnya = $cek[0]->lainnya;
        if($cekLainnya == 1){

            DB::table('tb_desa')->where('id',$id)->update([
                'nama_desa' => $namaDesa,
                'kepala_desa' => $kepalaDesa,
                'telp' => $telp,
                'alamat_desa' => $alamat,
                'status' => $status,
                'lainnya' => $lainnya,
                'created_at' => Carbon::now()
            ]);
        }else{
            DB::table('tb_desa')->where('id',$id)->update([
                'kode' => $codeDesa,
                'nama_desa' => $namaDesa,
                'kepala_desa' => $kepalaDesa,
                'telp' => $telp,
                'alamat_desa' => $alamat,
                'status' => $status,
                'lainnya' => $lainnya,
                'created_at' => Carbon::now()
            ]);
        }

        return redirect('pengaturan-desa')->with([
            'title' => 'Desa'
        ]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Pengaturan/PengaturanKecamatanController.php
<?php

namespace App\Http\Controllers\Pengaturan;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class PengaturanKecamatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::select('SELECT a.id,a.kode,a.nama_upk,a.alamat_upk,b.name as propinsi, c.name as kota, a.telp_upk,a.email_upk,a.website_upk,a.ketua_upk,a.sekretaris_upk,a.bendahara_upk,a.ketua_bkad,a.ketua_bpupk,a.logo_upk from tb_profil a, indonesia_provinces b, indonesia_cities c where a.propinsi_upk = b.id and a.kota_kab_upk = c.id');

        $count = DB::table('tb_profil')->count();
        return view('Pengaturan.Kecamatan.kecamatanShow',['data' => $data])->with([
            'title'=> 'Profile',
            'count' => $count
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Pengaturan/Desa/desaCreate.blade.php
@extends('layouts.master')

@section('title'){{$title}} @endsection

@section('css')
<!-- select2 css -->
<link href="{{ url('assets/libs/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />

<!-- dropzone css -->
<link href="{{ url('assets/libs/dropzone/dropzone.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

@component('components.breadcrumb')
@slot('li_1') Pengaturan @endslot
@slot('title') Tambah Desa/Kelurahan @endslot
@endcomponent
<form action="{{ route('pengaturan-desa.store') }}"  method="post" class="custom-validation">
    @csrf
<div class="row">
    <div class="col-12">

        <div class="card">
            <div class="card-body">

                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <div class="row">
                    <div class="col-sm-6">
                        <div class="mb-3">
                            <label for="nama">Nama Desa/Kelurahan</label>
                            <select class="form-control select2" name="desa" id="desa" required>
                                <option value="" selected disabled>-- Pilih Kelurahan/Desa</option>
                                @foreach ($desaCode as $desaCode)
                                    <option value="{{ $desaCode->code }}">{{ $desaCode->name }}</option>
                                @endforeach
                                <option value="other">Lainnya</option>
                            </select>
                        </div>
                        <div class="mb-3" id="fieldLainnya" style="display: none;">
                            <label for="desaLainnya">Kelurahan/Desa Lainnya</label>
                            <input type="text" class="form-control" name="desaLainnya" id="desaLainnya" placeholder="Lainnya">
                        </div>
                        <div class="mb-3">
                            <label for="alamat">Alamat Kantor</label>
                            <input id="alamat" name="alamat" type="text" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="telp">Telp</label>
                            <input id="telp" name="telp" type="text" class="form-control" required>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="mb-3">
                            <label for="kepalaDesa">Kepala Desa / Lurah</label>
                            <input id="kepalaDesa" name="kepalaDesa" type="text" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label for="status">Status</label>
                            <select name="status" class="form-control select2" required>
                                <option value="kelurahan">Kelurahan</option>
                                <option value="desa">Desa</option>
                            </select>
                        </div>
                    </div>
                    <div class="d-flex flex-wrap gap-2">
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Save Changes</button>
                        <button type="button" class="btn btn-secondary waves-effect waves-light">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
    <!-- end row -->

@endsection
@section('script')


<!-- select 2 plugin -->
<script src="{{ url('assets/libs/select2/select2.min.js') }}"></script>

<!-- dropzone plugin -->
<script src="{{ url('assets/libs/dropzone/dropzone.min.js') }}"></script>

<!-- init js -->
<script src="{{ url('assets/js/pages/ecommerce-select2.init.js') }}"></script>
<script src="{{ URL::asset('/assets/libs/parsleyjs/parsleyjs.min.js') }}"></script>
<script src="{{ URL::asset('/assets/js/pages/form-validation.init.js') }}"></script>
<script type="text/javascript">
    $('#desa').change(function(){
        var desa = $('#desa').val();
        if(desa == 'other'){
           $('#fieldLainnya').show();
           $('#desaLainnya').attr('required',true);
        }else{
            $('#fieldLainnya').hide();
            $('#desaLainnya').val('');
             $('#desaLainnya').attr('required',false);
        }
    })
  </script>

@endsection

resources/views/Pengaturan/Desa/desaShow.blade.php
@extends('layouts.master')

@section('title') {{ $title }} @endsection

@section('css')
    <!-- DataTables -->
    <link href="{{ URL::asset('/assets/libs/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    @component('components.breadcrumb')
        @slot('li_1') Pengaturan @endslot
        @slot('title') Desa @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @if ($message = Session::get('success'))
                    <div class="alert border-0 border-start border-5 border-primary alert-dismissible fade show">
                        <div>{{ $message }}</div>
                    </div>
	                @endif
                    {{-- <h4 class="card-title">Default Datatable</h4>
                    <p class="card-title-desc">DataTables has most features enabled by
                        default, so all you need to do to use it with your own tables is to call
                        the construction function: <code>$().DataTable();</code>.
                    </p> --}}
                    <p>


                        <a class="btn btn-primary btn-sm" href="{{ route('pengaturan-desa.create') }}">Tambah</a>
                    </p>
                    <table id="datatable" class="table table-bordered dt-responsive  nowrap w-100">
                        <thead>
                            <tr>
                                <th>Kode</th>
                                <th>Nama Desa</th>
                                <th>Alamat</th>
                                <th>Telp</th>
                                <th>Kepala Desa/Lurah</th>
                                <th>Jenis</th>
                                <th>Action</th>
                            </tr>
                        </thead>


                        <tbody>
                            @foreach ($data as $data )
                            <tr>
                                <td>{{ $data->kode }}</td>
                                <td>{{ $data->nama_desa }}</td>
                                <td>{{ $data->alamat_desa }}</td>
                                <td>{{ $data->telp }}</td>
                                <td>{{ $data->kepala_desa }}</td>
                                <td>{{ ucfirst($data->status) }}</td>
                                <td>
                                    <a class="btn btn-outline-primary btn-sm" href="{{ route('pengaturan-desa.edit',$data->id) }}">Edit</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->



@endsection
@section('script')
    <!-- Required datatable js -->
    <script src="{{ URL::asset('/assets/libs/datatables/datatables.min.js') }}"></script>
    <script src="{{ URL::asset('/assets/libs/jszip/jszip.min.js') }}"></script>
    <script src="{{ URL::asset('/assets/libs/pdfmake/pdfmake.min.js') }}"></script>
    <!-- Datatable init js -->
    <script src="{{ URL::asset('/assets/js/pages/datatables.init.js') }}"></script>
@endsection

resources/views/Pengaturan/Desa/editShow.blade.php
@extends('layouts.master')

@section('title') {{ $title }} @endsection

@section('css')
    <!-- DataTables -->
    <link href="{{ URL::asset('/assets/libs/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    @component('components.breadcrumb')
        @slot('li_1') Pengaturan @endslot
        @slot('title') Desa @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @if ($message = Session::get('success'))
                    <div class="alert border-0 border-start border-5 border-primary alert-dismissible fade show">
                        <div>{{ $message }}</div>
                    </div>
	                @endif
                    {{-- <h4 class="card-title">Default Datatable</h4>
                    <p class="card-title-desc">DataTables has most features enabled by
                        default, so all you need to do to use it with your own tables is to call
                        the construction function: <code>$().DataTable();</code>.
                    </p> --}}
                    <p>


                        <a class="btn btn-primary btn-sm" href="{{ route('pengaturan-desa.create') }}">Tambah</a>
                    </p>
                    <table id="datatable" class="table table-bordered dt-responsive  nowrap w-100">
                        <thead>
                            <tr>
                                <th>Kode</th>
                                <th>Nama Desa</th>
                                <th>Alamat</th>
                                <th>Telp</th>
                                <th>Kepala Desa/Lurah</th>
                                <th>Jenis</th>
                                <th>Action</th>
                            </tr>
                        </thead>


                        <tbody>
                            @foreach ($data as $data )
                            <tr>
                                <td>{{ $data->kode }}</td>
                                <td>{{ $data->nama_desa }}</td>
                                <td>{{ $data->alamat_desa }}</td>
                                <td>{{ $data->telp }}</td>
                                <td>{{ $data->kepala_desa }}</td>
                                <td>{{ ucfirst($data->status) }}</td>
                                <td>
                                    <a class="btn btn-outline-primary btn-sm" href="{{ route('pengaturan-desa.edit',$data->id) }}">Edit</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->



@endsection
@section('script')
    <!-- Required datatable js -->
    <script src="{{ URL::asset('/assets/libs/datatables/datatables.min.js') }}"></script>
    <script src="{{ URL::asset('/assets/libs/jszip/jszip.min.js') }}"></script>
    <script src="{{ URL::asset('/assets/libs/pdfmake/pdfmake.min.js') }}"></script>
    <!-- Datatable init js -->
    <script src="{{ URL::asset('/assets/js/pages/datatables.init.js') }}"></script>
@endsection