routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/config-clear', function () {
    Artisan::call('config:clear');
    return 'Configuration cache cleared!';
});

Route::get('/config-cache', function () {
    Artisan::call('config:cache');
    return 'Configuration cache cleared! <br> Configuration cached successfully!';
});

Route::get('/cache-clear', function () {
    Artisan::call('cache:clear');
    return 'Application cache cleared!';
});

Route::get('/view-cache', function () {
    Artisan::call('view:cache');
    return 'Compiled views cleared! <br> Blade templates cached successfully!';
});

Route::get('/view-clear', function () {
    Artisan::call('view:clear');
    return 'Compiled views cleared!';
});

Route::get('/route-cache', function () {
    Artisan::call('route:cache');
    return 'Route cache cleared! <br> Routes cached successfully!';
});

Route::get('/route-clear', function () {
    Artisan::call('route:clear');
    return 'Route cache cleared!';
});

Route::get('/storage-link', function () {
    Artisan::call('storage:link');
    return 'The links have been created.';
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'root'])->name('root');
// Route::get('/testing', [App\Http\Controllers\Pengaturan\PengaturanProfileController::class, 'index'])->name('index');

// Master Data
Route::resource('master-jenis-kegiatan', App\Http\Controllers\Master\MasterJenisKegiatanController::class);
Route::resource('master-jenis-usaha', App\Http\Controllers\Master\MasterJenisUsahaController::class);
Route::resource('master-pekerjaan', App\Http\Controllers\Master\MasterPekerjaanController::class);
Route::resource('master-agama', App\Http\Controllers\Master\MasterAgamaController::class);
Route::resource('master-kekeluargaan', App\Http\Controllers\Master\MasterKekeluargaanController::class);
Route::resource('master-status-perkawinan', App\Http\Controllers\Master\MasterStatusPerkawinanController::class);

//Update User Details
Route::post('/update-profile/{id}', [App\Http\Controllers\HomeController::class, 'updateProfile'])->name('updateProfile');
Route::post('/update-password/{id}', [App\Http\Controllers\HomeController::class, 'updatePassword'])->name('updatePassword');

// Route::get('{any}', [App\Http\Controllers\HomeController::class, 'index1'])->name('index1');

//Language Translation
Route::get('index/{locale}', [App\Http\Controllers\HomeController::class, 'lang']);

// Pengaturan
Route::resource('pengaturan-profile', App\Http\Controllers\Pengaturan\PengaturanProfileController::class);
Route::resource('pengaturan-kecamatan', App\Http\Controllers\Pengaturan\PengaturanKecamatanController::class);
Route::resource('pengaturan-desa', App\Http\Controllers\Pengaturan\PengaturanDesaController::class);
Route::prefix('pengaturan')->group(function () {
    Route::prefix('pengurus')->group(function () {
        Route::get('/', 'App\Http\Controllers\Pengaturan\PengurusController@index')->name('listPengurus');
        Route::get('/create', 'App\Http\Controllers\Pengaturan\PengurusController@create')->name('createPengurus');
        Route::get('/edit/{id}', 'App\Http\Controllers\Pengaturan\PengurusController@edit')->name('editPengurus');
        Route::post('/submit', 'App\Http\Controllers\Pengaturan\PengurusController@submit')->name('submitPengurus');
        Route::delete('/delete/{id}', 'App\Http\Controllers\Pengaturan\PengurusController@index')->name('deletePengurus');
    });
});

// Akuntansi
Route::prefix('akuntansi')->group(function (){
    Route::get('periode-akuntansi', 'App\Http\Controllers\Akuntansi\PeriodeAkuntansiController@index');
    Route::prefix('saldo-awal')->group(function (){
        Route::get('/', 'App\Http\Controllers\Akuntansi\SaldoAwalController@index');
        Route::get('/create', 'App\Http\Controllers\Akuntansi\SaldoAwalController@create');
        Route::post('/submit', 'App\Http\Controllers\Akuntansi\SaldoAwalController@submit')->name('saldoAwalSubmit');
    });
    Route::prefix('hibah')->group(function (){
        Route::get('/', 'App\Http\Controllers\Akuntansi\HibahController@index');
        Route::get('/create', 'App\Http\Controllers\Akuntansi\HibahController@create');
    });
    Route::prefix('tutup-buku')->group(function(){
        Route::get('/validator', 'App\Http\Controllers\Akuntansi\TutupBukuController@validator');
        Route::get('/pembagian-surplus', 'App\Http\Controllers\Akuntansi\TutupBukuController@pembagianSurplus');
        Route::get('/perubahan-surplus', 'App\Http\Controllers\Akuntansi\TutupBukuController@perubahanSurplus');
        Route::get('/saldo-awal', 'App\Http\Controllers\Akuntansi\TutupBukuController@saldoAwal');
        Route::get('/proses-tutup-buku', 'App\Http\Controllers\Akuntansi\TutupBukuController@tutupBuku');
        Route::get('/neraca-awal', 'App\Http\Controllers\Akuntansi\TutupBukuController@neracaAwal');
        Route::post('/neraca-awal', 'App\Http\Controllers\Akuntansi\TutupBukuController@laporanNeracaAwal')->name('laporanNeracaAwal');
    });
});

// User
Route::prefix('user')->group(function (){
    Route::get('/', 'App\Http\Controllers\User\UserController@index')->name('user.show');
    Route::get('/create', 'App\Http\Controllers\User\UserController@create')->name('userCreate');
    Route::post('/submit', 'App\Http\Controllers\User\UserController@submit')->name('userSubmit');
    Route::get('user-detail/{id}', 'App\Http\Controllers\User\UserController@userDetail')->name('user.detail');
    Route::get('user-edit/{id}', 'App\Http\Controllers\User\UserController@userEditDetail')->name('user.edit.detail');
    Route::post('edit', 'App\Http\Controllers\User\UserController@submitEdit')->name('user.update');
    Route::delete('delete/{id}', 'App\Http\Controllers\User\UserController@delete')->name('user.delete');
});


// Keanggotaan 
Route::resource('kelompok-list', App\Http\Controllers\Anggota\Kelompok\KelompokListController::class);
Route::resource('kelompok-anggota', App\Http\Controllers\Anggota\Kelompok\KelompokAnggotaController::class);
Route::resource('individu-anggota', App\Http\Controllers\Anggota\Individu\IndividuAnggotaController::class);

// Proposal
Route::resource('proposal-kelompok', App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class);
Route::post('/tambah-anggota', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'addMember'])->name('proposal-kelompok.add-member');
// Detail kelompok
Route::get('/proposal-kelompok/{id}/detail', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'detail'])->name('proposal-kelompok.detail');
// Registrasi Proposal
Route::post('/tambah-anggota', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'addMember'])->name('proposal-kelompok.add-member');
Route::get('/proposal-kelompok/{id}/register', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'registering'])->name('proposal-kelompok.registering');
Route::post('/proposal-kelompok/{id}/register', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'registerProcess'])->name('proposal-kelompok.register-process');
Route::get('/proposal-kelompok/{id}/dokumen', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'document'])->name('proposal-kelompok.register-document');
// Verifikasi Proposal
Route::get('/proposal-kelompok/{id}/verifikasi-anggota', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationMember'])->name('proposal-kelompok.verification-member');
Route::get('/proposal-kelompok/{id}/verifikasi', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationShow'])->name('proposal-kelompok.verification-show');
Route::post('/proposal-kelompok/{id}/verifikasi', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationProcess'])->name('proposal-kelompok.verification-process');
Route::get('/proposal-kelompok/{id}/rangkuman-verifikasi', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'verificationSummary'])->name('proposal-kelompok.verfication-summary');
// Penetapan Proposal
Route::get('/proposal-kelompok/{id}/penetapan', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'penetapanShow'])->name('proposal-kelompok.penetapan-show');
Route::post('/proposal-kelompok/{id}/penetapan', [App\Http\Controllers\Proposal\Kelompok\ProposalKelompokController::class, 'penetapanProcess'])->name('proposal-kelompok.penetapan-process');

// Pinjaman
Route::resource('pinjaman-kelompok', App\Http\Controllers\Pinjaman\Kelompok\PinjamanKelompokController::class);
// Detail pinjaman kelompok
Route::get('/pinjaman-kelompok-uep/{id}/detail', [App\Http\Controllers\Pinjaman\Kelompok\PinjamanKelompokController::class, 'detailUep'])->name('pinjaman-kelompok-uep.detail');
Route::get('/pinjaman-kelompok-spp/{id}/detail', [App\Http\Controllers\Pinjaman\Kelompok\PinjamanKelompokController::class, 'detailSpp'])->name('pinjaman-kelompok-spp.detail');
Route::resource('pinjaman-individu', App\Http\Controllers\Pinjaman\Individu\PinjamanIndividuController::class);


// Transaksi
Route::resource('angsuran-kelompok', App\Http\Controllers\Angsuran\Kelompok\PenerimaanAngsuranController::class);
Route::resource('angsuran-kelompok-uep', App\Http\Controllers\Angsuran\Kelompok\UEP\PenerimaanAngsuranUepController::class);

app/Http/Controllers/Master/MasterAgamaController.php
<?php

namespace App\Http\Controllers\Master;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class MasterAgamaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::table('m_agama')->get();
        return view('Master.Agama.agamaShow', ['data' => $data])->with([
            'title' => 'Master Agama'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Master.Agama.agamaCreate')->with([
            'title' => 'Create Agama'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'agama' => 'required|unique:m_agama,agama'
        ]);

        DB::table('m_agama')->insert([
            'agama' => $request->agama,
            'keterangan' => $request->keterangan,
            'created_at' => Carbon::now()
        ]);

        return redirect('master-agama')->with([
            'title' => 'Master Agama',
            'success' => 'Data Berhasil Ditambah'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('m_agama')->where('id',$id)->get();
        return view('Master.Agama.agamaEdit',['data' => $data])->with([
            'title' => 'Master Agama'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::table('m_agama')->where('id',$id)->update([
            'agama' => $request->agama,
            'keterangan' => $request->keterangan,
            'updated_at' => Carbon::now()
        ]);

        return redirect('master-agama')->with([
            'title' => 'Master Agama',
            'success' => 'Data Berhasil Di Update'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('m_agama')->where('id', $id)->delete();
        return redirect('master-agama')->with([
            'title' => 'Master Agama',
            'success' => 'Data Berhasil Dihapus'
        ]);
    }
}

app/Http/Controllers/Master/MasterJenisKegiatanController.php
<?php

namespace App\Http\Controllers\Master;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class MasterJenisKegiatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::table('m_jenis_kegiatan')->get();
        return view('Master.JenisKegiatan.jenisKegiatanShow', ['data' => $data])->with([
            'title' => 'Master Jenis Kegiatan'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Master.JenisKegiatan.jenisKegiatanCreate')->with([
            'title' => 'Create Jenis Kegiatan'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'jenisKegiatan' => 'required|unique:m_jenis_kegiatan,jenis_kegiatan'
        ]);

        DB::table('m_jenis_kegiatan')->insert([
            'jenis_kegiatan' => $request->jenisKegiatan,
            'keterangan' => $request->keterangan,
            'created_at' => Carbon::now()
        ]);

        return redirect('master-jenis-kegiatan')->with([
            'title' => 'Master Jenis Kegiatan',
            'success' => 'Data Berhasil Ditambah'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('m_jenis_kegiatan')->where('id',$id)->get();
        return view('Master.JenisKegiatan.jenisKegiatanEdit',['data' => $data])->with([
            'title' => 'Master Jenis Kegiatan'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::table('m_jenis_kegiatan')->where('id',$id)->update([
            'jenis_kegiatan' => $request->jenisKegiatan,
            'keterangan' => $request->keterangan,
            'updated_at' => Carbon::now()
        ]);

        return redirect('master-jenis-kegiatan')->with([
            'title' => 'Master Jenis Kegiatan',
            'success' => 'Data Berhasil Di Update'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('m_jenis_kegiatan')->where('id', $id)->delete();
        return redirect('master-jenis-kegiatan')->with([
            'title' => 'Master Jenis Kegiatan',
            'success' => 'Data Berhasil Dihapus'
        ]);
    }
}

resources/views/Master/StatusPerkawinan/statusPerkawinanCreate.blade.php
@extends('layouts.master')

@section('title'){{$title}} @endsection

@section('css')
<!-- select2 css -->
<link href="{{ url('assets/libs/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />

<!-- dropzone css -->
<link href="{{ url('assets/libs/dropzone/dropzone.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

@component('components.breadcrumb')
@slot('li_1') Master @endslot
@slot('title') Tambah Status Perkawinan @endslot
@endcomponent

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <form action="{{ route('master-status-perkawinan.store') }}" method="post" class="custom-validation">
                    @csrf
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="jenisKegiatan">Status Perkawinan</label>
                            <input type="text" class="form-control" name="status_perkawinan" id="status_perkawinan" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="keterangan">Keterangan</label>
                            <input id="keterangan" name="keterangan" type="text" class="form-control">
                        </div>
                        <div class="d-flex flex-wrap gap-2">
                            <button type="submit" class="btn btn-primary waves-effect waves-light">Save Changes</button>
                            <button type="button" class="btn btn-secondary waves-effect waves-light">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- end row -->

@endsection
@section('script')


<!-- select 2 plugin -->
<script src="{{ url('assets/libs/select2/select2.min.js') }}"></script>

<!-- dropzone plugin -->
<script src="{{ url('assets/libs/dropzone/dropzone.min.js') }}"></script>

<!-- init js -->
<script src="{{ url('assets/js/pages/ecommerce-select2.init.js') }}"></script>
<script src="{{ URL::asset('/assets/libs/parsleyjs/parsleyjs.min.js') }}"></script>
<script src="{{ URL::asset('/assets/js/pages/form-validation.init.js') }}"></script>
<script type="text/javascript">
    $('#desa').change(function () {
        var desa = $('#desa').val();
        if (desa == 'other') {
            $('#fieldLainnya').show();
            $('#desaLainnya').attr('required', true);
        } else {
            $('#fieldLainnya').hide();
            $('#desaLainnya').val('');
            $('#desaLainnya').attr('required', false);
        }
    })

</script>

@endsection

resources/views/Master/StatusPerkawinan/statusPerkawinanEdit.blade.php
@extends('layouts.master')

@section('title'){{$title}} @endsection

@section('css')
<!-- select2 css -->
<link href="{{ url('assets/libs/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />

<!-- dropzone css -->
<link href="{{ url('assets/libs/dropzone/dropzone.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

@component('components.breadcrumb')
@slot('li_1') Master @endslot
@slot('title') Edit Status Perkawinan @endslot
@endcomponent


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                @foreach ($data as $data )

                <form action="{{ route('master-status-perkawinan.update',$data->id) }}" method="post" class="custom-validation">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="jenisKegiatan">Status Perkawinan</label>
                            <input type="text" class="form-control" name="status_perkawinan" id="status_perkawinan" value="{{ $data->status_perkawinan }}" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="keterangan">Keterangan</label>
                            <input id="keterangan" name="keterangan" type="text" class="form-control" value="{{ $data->keterangan }}">
                        </div>
                        <div class="d-flex flex-wrap gap-2">
                            <button type="submit" class="btn btn-primary waves-effect waves-light">Save Changes</button>
                            <button type="button" class="btn btn-secondary waves-effect waves-light">Cancel</button>
                        </div>
                    </div>
                </form>
                @endforeach
            </div>
        </div>
    </div>
</div>
<!-- end row -->

@endsection
@section('script')


<!-- select 2 plugin -->
<script src="{{ url('assets/libs/select2/select2.min.js') }}"></script>

<!-- dropzone plugin -->
<script src="{{ url('assets/libs/dropzone/dropzone.min.js') }}"></script>

<!-- init js -->
<script src="{{ url('assets/js/pages/ecommerce-select2.init.js') }}"></script>
<script src="{{ URL::asset('/assets/libs/parsleyjs/parsleyjs.min.js') }}"></script>
<script src="{{ URL::asset('/assets/js/pages/form-validation.init.js') }}"></script>
<script type="text/javascript">
    $('#desa').change(function () {
        var desa = $('#desa').val();
        if (desa == 'other') {
            $('#fieldLainnya').show();
            $('#desaLainnya').attr('required', true);
        } else {
            $('#fieldLainnya').hide();
            $('#desaLainnya').val('');
            $('#desaLainnya').attr('required', false);
        }
    })

</script>

@endsection

resources/views/Master/StatusPerkawinan/statusPerkawinanShow.blade.php
@extends('layouts.master')

@section('title') {{ $title }} @endsection

@section('css')
    <!-- DataTables -->
    <link href="{{ URL::asset('/assets/libs/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    @component('components.breadcrumb')
        @slot('li_1') Master @endslot
        @slot('title') Status Perkawinan @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @if ($message = Session::get('success'))
                    <div class="alert border-0 border-start border-5 border-primary alert-dismissible fade show">
                        <div>{{ $message }}</div>
                    </div>
	                @endif
                    {{-- <h4 class="card-title">Default Datatable</h4>
                    <p class="card-title-desc">DataTables has most features enabled by
                        default, so all you need to do to use it with your own tables is to call
                        the construction function: <code>$().DataTable();</code>.
                    </p> --}}
                    <p>


                        <a class="btn btn-primary btn-sm" href="{{ route('master-status-perkawinan.create') }}">Tambah</a>
                    </p>
                    <table id="datatable" class="table table-bordered dt-responsive  nowrap w-100">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Status Perkawinan</th>
                                <th>Keterangan</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        @php
                            $i = 1;
                        @endphp
                        <tbody>
                            @foreach ($data as $data )
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $data->status_perkawinan }}</td>
                                <td>{{ $data->keterangan }}</td>
                                <td>
                                    <form action="{{ route('master-status-perkawinan.destroy',$data->id) }}" method="POST">
                                    <a class="btn btn-outline-primary btn-sm" href="{{ route('master-status-perkawinan.edit',$data->id) }}">Edit</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->



@endsection
@section('script')
    <!-- Required datatable js -->
    <script src="{{ URL::asset('/assets/libs/datatables/datatables.min.js') }}"></script>
    <script src="{{ URL::asset('/assets/libs/jszip/jszip.min.js') }}"></script>
    <script src="{{ URL::asset('/assets/libs/pdfmake/pdfmake.min.js') }}"></script>
    <!-- Datatable init js -->
    <script src="{{ URL::asset('/assets/js/pages/datatables.init.js') }}"></script>
@endsection